### ISSUE TITLE
rcon.command() needs to be called twice?

### ISSUE THREAD

**Issue by nop** [Kronos666/rkon-core#5]
This may just be an issue I'm having, but here's my setup:

My program has a TextField (calls ActionEvent when Enter is pressed) which contains the following code:
```java
String text = getTextField().getText().trim();
	if (!text.isEmpty()) {
		try {
			System.out.println(rcon.command(text));
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		getTextField().setText("");
	}
```
I need to input text twice for rcon.command() to work. Well, my initial command isn't printed, then after that all subsequent commands are printed, but behind by one command.

**Comment by kr5ch** [comment]
I will look into this later today. What type of server are you connecting to ?

**Comment by kr5ch** [comment]
I cannot reproduce your problem. Please provide more infos.

**Comment by nop** [comment]
I'm connecting to an Insurgency server. I have to call command() twice. Once, I use it in a TextField's ActionPerformed() method, so that may be part of the cause, but I couldn't figure it out. Another time, I just run rcon.command("status") twice to pull my user's info outside of any control statements. I went through it step-by-step in my debugger, and it looks like the command is sent, but not returned until the second call, if that makes sense. As if the command is sent, but the returned strings are returned one command too late.

**Comment by kr5ch** [comment]
There is nothing in the code of rkon-core that could be buffering the last command received so it must be either your Insurgency server acting strange or the graphical interface of your program not refreshing at the right time.

**Comment by nop** [comment]
It may be the way I'm writing my code. I've made a barebones, terminal-based app to demo this, and this may be the culprit:
```java
try {
	BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
	while (true) {
		System.out.println(rcon.command(reader.readLine()));
	}
} catch (IOException e) {
	e.printStackTrace();
}
```
EDIT: Here's a better explanation of my issue. When doing `String str = rcon.command("status");` the string's value is "", but after assigning it to another `rcon.command(<anything here>)`, it becomes what the first line should have returned. Then, the next `rcon.command()` assigned to `str` becomes what `rcon.command(<anything here>)` should have returned.

**Comment by nop** [comment]
Additionally, if I were to use your latest jar release instead of your source, how would I attribute the code to you? In other words, what would be the appropriate way to include your license alongside my own?

**Comment by nop** [comment]
Authentication code was incorrect. #7 fixes it.

**Comment by obiasutti** [comment]
The rcon-socket is not expected to behave like a synchronize input-output channel.  

As from the documentation:

> An RCON connection can have multiple outstanding requests at any given time; it is not necessary to wait for a response to one request before writing another. These requests are guaranteed to be executed in the order they are received, and responses will be sent out in the same order.

The problem is that the implementation here does exaclty a sync input-output handling of the socket.

The reader must be a async-worker that reads uninterruptedly the stream, inserting tuples of {id, packetResponse} into a (concurrent)-map. The Requester can then fetch the response later... 

BUT... he would not know which response is his... so...

another problem here is that the "requestId" (which is actually a packetId) is being generated only once for each rcon-connection lifetime. This ID is the way RCON offers a response to matched to request, by resending the same value issued by the client. Therefore it should be regenerated for each request.

The final an more crucial problem is that the RCON server is responding to the AUTH call twice! 

That's why you are having this delay experience with the responses. Since there is no tracking mechanism in this code, it simply assumes that the next packet is the response from the command you just issued.

A quick and dirty solution is to change the code of the RconPacket.send(..) method to recall the read method if the packet is a SERVER_AUTH.
`if(type == SERVERDATA_AUTH) {`
`	RconPacket.read(rcon.getSocket().getInputStream());`
`}`
`return RconPacket.read(rcon.getSocket().getInputStream());`

Cheers!

**Comment by kr5ch** [comment]
I am archiving this project, you are of course free to make forks according to the license.
